services:
  web:
    build:
        context: ./src
        dockerfile: WebApi/Dockerfile
    ports:
      - "7000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqldata;Database=ECommerce;User=sa;Password=Pass@word;TrustServerCertificate=True
    depends_on:
        - sqldata
  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - ./database/data:/var/opt/mssql/data
      - ./database/log:/var/opt/mssql/log
      - ./database/secrets:/var/opt/mssql/secrets
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "false"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.22
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: elasticsearch:9200
    depends_on:
      - elasticsearch