services:
  web:
    build:
        context: ./src
        dockerfile: WebApi/Dockerfile
    ports:
      - "7000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
        - sqldata
  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - ./database/data:/var/opt/mssql/data
      - ./database/log:/var/opt/mssql/log
      - ./database/secrets:/var/opt/mssql/secrets
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"